version: '3.7'

services:
  mariadb:
    image: mariadb:10.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - appwrite-mariadb:/var/lib/mysql

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - appwrite-redis:/data

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  appwrite:
    image: appwrite/appwrite:1.6.2
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    environment:
      _APP_ENV: production
    ports:
      - "80:80"

volumes:
  appwrite-mariadb:
  appwrite-redis: {}
