services:
  mariadb:
    image: mariadb:10.11
    container_name: lumi-mariadb
    restart: unless-stopped
    networks:
      appwrite:
        aliases:
          - console
          - db_main
          - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: appwrite-password
      MYSQL_DATABASE: appwrite
      MYSQL_USER: appwrite-user
      MYSQL_PASSWORD: appwrite-password
    volumes:
      - appwrite-mariadb:/var/lib/mysql:rw
    command: 'mysqld --innodb-flush-method=fsync'

  redis:
    image: redis:7.2-alpine
    container_name: lumi-redis
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-redis:/data:rw

  mailhog:
    image: mailhog/mailhog
    container_name: lumi-mailhog
    restart: unless-stopped
    networks:
      - appwrite
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  appwrite:
    image: appwrite/appwrite:1.6.2
    container_name: lumi-appwrite
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - mariadb
      - redis
    environment:
      _APP_ENV: production
      _APP_DOMAIN: 192.168.68.170,localhost
      _APP_DOMAIN_TARGET: 192.168.68.170
      _APP_DOMAIN_FUNCTIONS: functions.lumi.test
      _APP_OPENSSL_KEY_V1: example-secret-key
      _APP_DB_HOST: console
      _APP_DB_PORT: 3306
      _APP_DB_SCHEMA: appwrite
      _APP_DB_USER: appwrite-user
      _APP_DB_PASS: appwrite-password
      _APP_CONNECTIONS_DB_LOGS: db_main=mariadb://appwrite-user:appwrite-password@console:3306/appwrite
      _APP_CONNECTIONS_DB_CONSOLE: db_main=mariadb://appwrite-user:appwrite-password@console:3306/appwrite
      _APP_CONNECTIONS_DB_DATABASE: db_main=mariadb://appwrite-user:appwrite-password@console:3306/appwrite
      _APP_REDIS_HOST: redis
      _APP_REDIS_PORT: 6379
      _APP_STORAGE_LIMIT: 10000000
      _APP_OPTIONS_ABUSE: disabled
      _APP_CONSOLE_WHITELIST_ROOT: disabled
    ports:
      - "80:80"
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
      - appwrite-functions:/storage/functions:rw

  worker-databases:
    image: appwrite/appwrite:1.6.2
    container_name: lumi-worker-databases
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
      - mariadb
    environment:
      _APP_ENV: production
      _APP_REDIS_HOST: redis
      _APP_REDIS_PORT: 6379
      _APP_DB_HOST: console
      _APP_DB_PORT: 3306
      _APP_DB_SCHEMA: appwrite
      _APP_DB_USER: appwrite-user
      _APP_DB_PASS: appwrite-password
      _APP_CONNECTIONS_DB_LOGS: db_main=mariadb://appwrite-user:appwrite-password@console:3306/appwrite
      _APP_CONNECTIONS_DB_CONSOLE: db_main=mariadb://appwrite-user:appwrite-password@console:3306/appwrite
      _APP_CONNECTIONS_DB_DATABASE: db_main=mariadb://appwrite-user:appwrite-password@console:3306/appwrite
    command: worker-databases

networks:
  appwrite:

volumes:
  appwrite-mariadb:
  appwrite-redis:
  appwrite-uploads:
  appwrite-cache:
  appwrite-config:
  appwrite-certificates:
  appwrite-functions:
