// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'inference.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `complete`, `fmt`, `fmt`

class AgentChunk {
  final String token;
  final bool isFinal;
  final double tokensPerSecond;

  const AgentChunk({
    required this.token,
    required this.isFinal,
    required this.tokensPerSecond,
  });

  @override
  int get hashCode =>
      token.hashCode ^ isFinal.hashCode ^ tokensPerSecond.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentChunk &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          isFinal == other.isFinal &&
          tokensPerSecond == other.tokensPerSecond;
}

/// LumiAgent is a thin wrapper that will later integrate with Rig's Agent.
/// For Phase 3 scaffold it initializes the rig-core and provides a simple
/// completion helper that collects inference chunks into a single String.
class LumiAgent {
  final String id;

  const LumiAgent({
    required this.id,
  });

  /// Asynchronously request a completion for `prompt` using the provided
  /// `ModelTier`. This function collects streamed `InferenceChunk`s from the
  /// inference module and concatenates tokens with spaces. A timeout is
  /// enforced to avoid hanging the caller.
  Future<String> complete({required String prompt, required ModelTier tier}) =>
      RustLib.instance.api
          .crateAgentLumiAgentComplete(that: this, prompt: prompt, tier: tier);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Construct a new LumiAgent. Register this agent as the rig-core
  /// CompletionProvider so higher-level code can call into Rig to obtain
  /// completions that are routed through LiteRT-LM.
  static Future<LumiAgent> newInstance() =>
      RustLib.instance.api.crateAgentLumiAgentNew();

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LumiAgent && runtimeType == other.runtimeType && id == other.id;
}
