// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'agent.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FRB-facing agent chat entrypoint (scaffold)
/// Spawns a background task that runs the current inference stream and
/// forwards InferenceChunk -> AgentChunk into the provided sink.
Stream<AgentChunk> agentChat({required String prompt}) =>
    RustLib.instance.api.crateAgentFrbAgentChat(prompt: prompt);
