// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Returns the build timestamp as an ISO 8601 string.
Future<void> buildTimestamp() =>
    RustLib.instance.api.crateBuildSupportBuildTimestamp();

/// Returns the build profile (debug/release).
Future<void> buildProfile() =>
    RustLib.instance.api.crateBuildSupportBuildProfile();
