// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the SQLite schema for Lumi core.
///
/// This creates the following tables if they do not already exist:
/// - transactions
/// - mileage_logs
/// - users
///
/// Two helper functions are provided:
/// - db_init_with_pool(pool: &SqlitePool) -> Result<(), sqlx::Error>
/// - db_init(db_url: &str) -> Result<(), sqlx::Error>
Future<void> dbInitWithPool({required SqlitePool pool}) =>
    RustLib.instance.api.crateDbDbInitWithPool(pool: pool);

Future<void> dbInit({required String dbUrl}) =>
    RustLib.instance.api.crateDbDbInit(dbUrl: dbUrl);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SqlitePool>>
abstract class SqlitePool implements RustOpaqueInterface {}
