// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tools.dart';

/// Produce a deterministic placeholder embedding vector (length 768) for a transaction.
/// This is a temporary, deterministic embedding generator used until the real
/// LiteRT-LM embedding pipeline is available.
Future<Float32List> embedTransaction(
        {required String vendor,
        required String category,
        required double amount,
        required String date}) =>
    RustLib.instance.api.crateEmbeddingsEmbedTransaction(
        vendor: vendor, category: category, amount: amount, date: date);

/// Convenience wrapper: embed from a TransactionSummary struct.
/// Builds the canonical string "{vendor} {category} {amount} {date}" where date is RFC3339.
Future<Float32List> embedTransactionFromSummary(
        {required TransactionSummary tx}) =>
    RustLib.instance.api.crateEmbeddingsEmbedTransactionFromSummary(tx: tx);

/// Produce a deterministic placeholder embedding vector (length 768) for arbitrary text.
/// Mirrors the approach used for transactions so unit tests can run without model deps.
Future<Float32List> embedText({required String text}) =>
    RustLib.instance.api.crateEmbeddingsEmbedText(text: text);
