// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'build_support.dart';
import 'dart:async';
import 'dart:convert';
import 'db.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'inference.dart';
import 'lib.dart';
import 'model_registry.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'validators.dart';
import 'vector_db.dart';


                /// Main entrypoint of the Rust API
                class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
                  @internal
                  static final instance = RustLib._();

                  RustLib._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    RustLibApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                    bool forceSameCodegenVersion = true,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                      forceSameCodegenVersion: forceSameCodegenVersion,
                    );
                  }

                  /// Initialize flutter_rust_bridge in mock mode.
                  /// No libraries for FFI are loaded.
                  static void initMock({
                    required RustLibApi api,
                  }) {
                    instance.initMockImpl(
                      api: api,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

                  @override
                  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    
                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.11.1';

                  @override
                  int get rustContentHash => -459107880;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'lumi_core',
                    ioDirectory: 'rust/lumi_core/target/release/',
                    webPrefix: 'pkg/',
                  );
                }
                

                abstract class RustLibApi extends BaseApi {
                  PathBuf crateModelRegistryModelRegistryAutoAccessorGetBaseDir({required ModelRegistry that });

void crateModelRegistryModelRegistryAutoAccessorSetBaseDir({required ModelRegistry that , required PathBuf baseDir });

Future<PathBuf> crateModelRegistryModelRegistryModelPath({required ModelRegistry that , required String modelId });

Future<void> crateBuildSupportBuildProfile();

Future<void> crateBuildSupportBuildTimestamp();

Future<bool> crateModelRegistryCheckModelReady({required Path baseDir , required String modelId , Str? expectedSha256 });

Future<String> crateModelRegistryComputeSha256({required Path path });

Future<void> crateCrateVersion();

Future<void> crateDbDbInit({required String dbUrl });

Future<void> crateDbDbInitWithPool({required SqlitePool pool });

Future<bool> crateModelRegistryFrbCheckModelReady({required String modelId , String? expectedSha256 });

Future<double> crateModelRegistryFrbGetDownloadProgress({required String modelId });

Future<void> crateInferenceFrbLoadModel({required String modelId });

Future<String> crateInferenceFrbSelectModelTier({required List<String> hints });

Future<double> crateModelRegistryGetDownloadProgress({required String modelId });

Future<(Float32List,String)> crateVectorDbGetEmbedding({required String dbPath , required String id });

Stream<InferenceChunk> crateInferenceInferStream({required String prompt , required ModelTier modelTier });

Future<InferenceEngine> crateInferenceInferenceEngineFromStrings({required String model , required String backend });

Future<InferenceEngine> crateInferenceInferenceEngineLoad({required String modelId , required String modelPath });

Future<InferenceEngine> crateInferenceInferenceEngineNew({required ModelId modelId , required LiteRtSession session });

Future<LiteRtSession> crateInferenceLiteRtSessionNew({required String backend });

Future<String> cratePing();

Future<ModelTier> crateInferenceSelectModelTierFromHints({required List<String> hints });

Future<void> crateVectorDbUpsertEmbedding({required String dbPath , required String id , required List<double> embedding , required String metadata });

Future<bool> crateValidatorsValidateEmail({required String email });

Future<bool> crateValidatorsValidatePassword({required String password });

Future<bool> crateValidatorsValidateTerms({required bool accepted });

Future<void> crateVectorDbVectorDbInit({required String dbPath });

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_BoxError;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_BoxError;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_BoxErrorPtr;

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_BoxError;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_BoxError;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_BoxErrorPtr;

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_ModelRegistry;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_ModelRegistry;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ModelRegistryPtr;

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Path;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Path;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_PathPtr;

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_PathBuf;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_PathBuf;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_PathBufPtr;

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_SqlitePool;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_SqlitePool;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SqlitePoolPtr;

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Str;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Str;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_StrPtr;


                }
                

                class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
                  RustLibApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override PathBuf crateModelRegistryModelRegistryAutoAccessorGetBaseDir({required ModelRegistry that })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(that, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateModelRegistryModelRegistryAutoAccessorGetBaseDirConstMeta,
            argValues: [that],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateModelRegistryModelRegistryAutoAccessorGetBaseDirConstMeta => const TaskConstMeta(
            debugName: "ModelRegistry_auto_accessor_get_base_dir",
            argNames: ["that"],
        );
        

@override void crateModelRegistryModelRegistryAutoAccessorSetBaseDir({required ModelRegistry that , required PathBuf baseDir })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(that, serializer);
sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf(baseDir, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateModelRegistryModelRegistryAutoAccessorSetBaseDirConstMeta,
            argValues: [that, baseDir],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateModelRegistryModelRegistryAutoAccessorSetBaseDirConstMeta => const TaskConstMeta(
            debugName: "ModelRegistry_auto_accessor_set_base_dir",
            argNames: ["that", "baseDir"],
        );
        

@override Future<PathBuf> crateModelRegistryModelRegistryModelPath({required ModelRegistry that , required String modelId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(that, serializer);
sse_encode_String(modelId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateModelRegistryModelRegistryModelPathConstMeta,
            argValues: [that, modelId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateModelRegistryModelRegistryModelPathConstMeta => const TaskConstMeta(
            debugName: "ModelRegistry_model_path",
            argNames: ["that", "modelId"],
        );
        

@override Future<void> crateBuildSupportBuildProfile()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateBuildSupportBuildProfileConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateBuildSupportBuildProfileConstMeta => const TaskConstMeta(
            debugName: "build_profile",
            argNames: [],
        );
        

@override Future<void> crateBuildSupportBuildTimestamp()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateBuildSupportBuildTimestampConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateBuildSupportBuildTimestampConstMeta => const TaskConstMeta(
            debugName: "build_timestamp",
            argNames: [],
        );
        

@override Future<bool> crateModelRegistryCheckModelReady({required Path baseDir , required String modelId , Str? expectedSha256 })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPath(baseDir, serializer);
sse_encode_String(modelId, serializer);
sse_encode_opt_box_autoadd_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(expectedSha256, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateModelRegistryCheckModelReadyConstMeta,
            argValues: [baseDir, modelId, expectedSha256],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateModelRegistryCheckModelReadyConstMeta => const TaskConstMeta(
            debugName: "check_model_ready",
            argNames: ["baseDir", "modelId", "expectedSha256"],
        );
        

@override Future<String> crateModelRegistryComputeSha256({required Path path })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPath(path, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateModelRegistryComputeSha256ConstMeta,
            argValues: [path],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateModelRegistryComputeSha256ConstMeta => const TaskConstMeta(
            debugName: "compute_sha256",
            argNames: ["path"],
        );
        

@override Future<void> crateCrateVersion()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateCrateVersionConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateCrateVersionConstMeta => const TaskConstMeta(
            debugName: "crate_version",
            argNames: [],
        );
        

@override Future<void> crateDbDbInit({required String dbUrl })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(dbUrl, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateDbDbInitConstMeta,
            argValues: [dbUrl],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateDbDbInitConstMeta => const TaskConstMeta(
            debugName: "db_init",
            argNames: ["dbUrl"],
        );
        

@override Future<void> crateDbDbInitWithPool({required SqlitePool pool })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlitePool(pool, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateDbDbInitWithPoolConstMeta,
            argValues: [pool],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateDbDbInitWithPoolConstMeta => const TaskConstMeta(
            debugName: "db_init_with_pool",
            argNames: ["pool"],
        );
        

@override Future<bool> crateModelRegistryFrbCheckModelReady({required String modelId , String? expectedSha256 })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(modelId, serializer);
sse_encode_opt_String(expectedSha256, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateModelRegistryFrbCheckModelReadyConstMeta,
            argValues: [modelId, expectedSha256],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateModelRegistryFrbCheckModelReadyConstMeta => const TaskConstMeta(
            debugName: "frb_check_model_ready",
            argNames: ["modelId", "expectedSha256"],
        );
        

@override Future<double> crateModelRegistryFrbGetDownloadProgress({required String modelId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(modelId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateModelRegistryFrbGetDownloadProgressConstMeta,
            argValues: [modelId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateModelRegistryFrbGetDownloadProgressConstMeta => const TaskConstMeta(
            debugName: "frb_get_download_progress",
            argNames: ["modelId"],
        );
        

@override Future<void> crateInferenceFrbLoadModel({required String modelId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(modelId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        )
        ,
            constMeta: kCrateInferenceFrbLoadModelConstMeta,
            argValues: [modelId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateInferenceFrbLoadModelConstMeta => const TaskConstMeta(
            debugName: "frb_load_model",
            argNames: ["modelId"],
        );
        

@override Future<String> crateInferenceFrbSelectModelTier({required List<String> hints })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_String(hints, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateInferenceFrbSelectModelTierConstMeta,
            argValues: [hints],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateInferenceFrbSelectModelTierConstMeta => const TaskConstMeta(
            debugName: "frb_select_model_tier",
            argNames: ["hints"],
        );
        

@override Future<double> crateModelRegistryGetDownloadProgress({required String modelId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(modelId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateModelRegistryGetDownloadProgressConstMeta,
            argValues: [modelId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateModelRegistryGetDownloadProgressConstMeta => const TaskConstMeta(
            debugName: "get_download_progress",
            argNames: ["modelId"],
        );
        

@override Future<(Float32List,String)> crateVectorDbGetEmbedding({required String dbPath , required String id })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(dbPath, serializer);
sse_encode_String(id, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_record_list_prim_f_32_strict_string,
          decodeErrorData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError,
        )
        ,
            constMeta: kCrateVectorDbGetEmbeddingConstMeta,
            argValues: [dbPath, id],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateVectorDbGetEmbeddingConstMeta => const TaskConstMeta(
            debugName: "get_embedding",
            argNames: ["dbPath", "id"],
        );
        

@override Stream<InferenceChunk> crateInferenceInferStream({required String prompt , required ModelTier modelTier })  { 
            final sink = RustStreamSink<InferenceChunk>();
            unawaited(handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(prompt, serializer);
sse_encode_model_tier(modelTier, serializer);
sse_encode_StreamSink_inference_chunk_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        )
        ,
            constMeta: kCrateInferenceInferStreamConstMeta,
            argValues: [prompt, modelTier, sink],
            apiImpl: this,
        )));
            return sink.stream;
             }


        TaskConstMeta get kCrateInferenceInferStreamConstMeta => const TaskConstMeta(
            debugName: "infer_stream",
            argNames: ["prompt", "modelTier", "sink"],
        );
        

@override Future<InferenceEngine> crateInferenceInferenceEngineFromStrings({required String model , required String backend })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(model, serializer);
sse_encode_String(backend, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_inference_engine,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateInferenceInferenceEngineFromStringsConstMeta,
            argValues: [model, backend],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateInferenceInferenceEngineFromStringsConstMeta => const TaskConstMeta(
            debugName: "inference_engine_from_strings",
            argNames: ["model", "backend"],
        );
        

@override Future<InferenceEngine> crateInferenceInferenceEngineLoad({required String modelId , required String modelPath })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(modelId, serializer);
sse_encode_String(modelPath, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_inference_engine,
          decodeErrorData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxErrorSendSync,
        )
        ,
            constMeta: kCrateInferenceInferenceEngineLoadConstMeta,
            argValues: [modelId, modelPath],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateInferenceInferenceEngineLoadConstMeta => const TaskConstMeta(
            debugName: "inference_engine_load",
            argNames: ["modelId", "modelPath"],
        );
        

@override Future<InferenceEngine> crateInferenceInferenceEngineNew({required ModelId modelId , required LiteRtSession session })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_model_id(modelId, serializer);
sse_encode_box_autoadd_lite_rt_session(session, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_inference_engine,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateInferenceInferenceEngineNewConstMeta,
            argValues: [modelId, session],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateInferenceInferenceEngineNewConstMeta => const TaskConstMeta(
            debugName: "inference_engine_new",
            argNames: ["modelId", "session"],
        );
        

@override Future<LiteRtSession> crateInferenceLiteRtSessionNew({required String backend })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(backend, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_lite_rt_session,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateInferenceLiteRtSessionNewConstMeta,
            argValues: [backend],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateInferenceLiteRtSessionNewConstMeta => const TaskConstMeta(
            debugName: "lite_rt_session_new",
            argNames: ["backend"],
        );
        

@override Future<String> cratePing()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCratePingConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCratePingConstMeta => const TaskConstMeta(
            debugName: "ping",
            argNames: [],
        );
        

@override Future<ModelTier> crateInferenceSelectModelTierFromHints({required List<String> hints })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_String(hints, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_model_tier,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateInferenceSelectModelTierFromHintsConstMeta,
            argValues: [hints],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateInferenceSelectModelTierFromHintsConstMeta => const TaskConstMeta(
            debugName: "select_model_tier_from_hints",
            argNames: ["hints"],
        );
        

@override Future<void> crateVectorDbUpsertEmbedding({required String dbPath , required String id , required List<double> embedding , required String metadata })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(dbPath, serializer);
sse_encode_String(id, serializer);
sse_encode_list_prim_f_32_loose(embedding, serializer);
sse_encode_String(metadata, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError,
        )
        ,
            constMeta: kCrateVectorDbUpsertEmbeddingConstMeta,
            argValues: [dbPath, id, embedding, metadata],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateVectorDbUpsertEmbeddingConstMeta => const TaskConstMeta(
            debugName: "upsert_embedding",
            argNames: ["dbPath", "id", "embedding", "metadata"],
        );
        

@override Future<bool> crateValidatorsValidateEmail({required String email })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(email, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateValidatorsValidateEmailConstMeta,
            argValues: [email],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateValidatorsValidateEmailConstMeta => const TaskConstMeta(
            debugName: "validate_email",
            argNames: ["email"],
        );
        

@override Future<bool> crateValidatorsValidatePassword({required String password })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(password, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateValidatorsValidatePasswordConstMeta,
            argValues: [password],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateValidatorsValidatePasswordConstMeta => const TaskConstMeta(
            debugName: "validate_password",
            argNames: ["password"],
        );
        

@override Future<bool> crateValidatorsValidateTerms({required bool accepted })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_bool(accepted, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateValidatorsValidateTermsConstMeta,
            argValues: [accepted],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateValidatorsValidateTermsConstMeta => const TaskConstMeta(
            debugName: "validate_terms",
            argNames: ["accepted"],
        );
        

@override Future<void> crateVectorDbVectorDbInit({required String dbPath })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(dbPath, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateVectorDbVectorDbInitConstMeta,
            argValues: [dbPath],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateVectorDbVectorDbInitConstMeta => const TaskConstMeta(
            debugName: "vector_db_init",
            argNames: ["dbPath"],
        );
        

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_BoxError => wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_BoxError => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError;

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_BoxError => wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxErrorSendSync;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_BoxError => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxErrorSendSync;

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_ModelRegistry => wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_ModelRegistry => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry;

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Path => wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPath;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Path => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPath;

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_PathBuf => wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_PathBuf => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf;

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_SqlitePool => wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlitePool;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_SqlitePool => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlitePool;

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Str => wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Str => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr;



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return AnyhowException(raw as String); }

@protected BoxError dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return BoxErrorImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected BoxError dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxErrorSendSync(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return BoxErrorImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected ModelRegistry dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return ModelRegistryImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected PathBuf dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return PathBufImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected ModelRegistry dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return ModelRegistryImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected ModelRegistry dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return ModelRegistryImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected Path dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPath(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return PathImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected SqlitePool dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlitePool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return SqlitePoolImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected Str dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return StrImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected BoxError dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return BoxErrorImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected BoxError dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxErrorSendSync(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return BoxErrorImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected ModelRegistry dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return ModelRegistryImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected Path dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPath(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return PathImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected PathBuf dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return PathBufImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected SqlitePool dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlitePool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return SqlitePoolImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected Str dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return StrImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected RustStreamSink<InferenceChunk> dco_decode_StreamSink_inference_chunk_Sse(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
throw UnimplementedError(); }

@protected String dco_decode_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as String; }

@protected bool dco_decode_bool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as bool; }

@protected Str dco_decode_box_autoadd_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(raw); }

@protected LiteRtSession dco_decode_box_autoadd_lite_rt_session(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_lite_rt_session(raw); }

@protected double dco_decode_f_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as double; }

@protected int dco_decode_i_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected InferenceChunk dco_decode_inference_chunk(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
                return InferenceChunk(token: dco_decode_String(arr[0]),
isFinal: dco_decode_bool(arr[1]),
tokensPerSecond: dco_decode_f_32(arr[2]),); }

@protected InferenceEngine dco_decode_inference_engine(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
                return InferenceEngine(modelId: dco_decode_model_id(arr[0]),
session: dco_decode_lite_rt_session(arr[1]),); }

@protected List<String> dco_decode_list_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_String).toList(); }

@protected List<double> dco_decode_list_prim_f_32_loose(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as List<double>; }

@protected Float32List dco_decode_list_prim_f_32_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Float32List; }

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint8List; }

@protected LiteRtSession dco_decode_lite_rt_session(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 1) throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
                return LiteRtSession(backend: dco_decode_String(arr[0]),); }

@protected ModelId dco_decode_model_id(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return ModelId.values[raw as int]; }

@protected ModelTier dco_decode_model_tier(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return ModelTier.values[raw as int]; }

@protected String? dco_decode_opt_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw == null ? null : dco_decode_String(raw); }

@protected Str? dco_decode_opt_box_autoadd_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw == null ? null : dco_decode_box_autoadd_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(raw); }

@protected (Float32List,String) dco_decode_record_list_prim_f_32_strict_string(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
            if (arr.length != 2) {
                throw Exception('Expected 2 elements, got ${arr.length}');
            }
            return (dco_decode_list_prim_f_32_strict(arr[0]),dco_decode_String(arr[1]),); }

@protected int dco_decode_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected void dco_decode_unit(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return; }

@protected BigInt dco_decode_usize(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeU64(raw); }

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_String(deserializer);
        return AnyhowException(inner); }

@protected BoxError sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return BoxErrorImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected BoxError sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxErrorSendSync(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return BoxErrorImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected ModelRegistry sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return ModelRegistryImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected PathBuf sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return PathBufImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected ModelRegistry sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return ModelRegistryImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected ModelRegistry sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return ModelRegistryImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected Path sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPath(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return PathImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected SqlitePool sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlitePool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return SqlitePoolImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected Str sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return StrImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected BoxError sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return BoxErrorImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected BoxError sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxErrorSendSync(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return BoxErrorImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected ModelRegistry sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return ModelRegistryImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected Path sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPath(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return PathImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected PathBuf sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return PathBufImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected SqlitePool sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlitePool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return SqlitePoolImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected Str sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return StrImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected RustStreamSink<InferenceChunk> sse_decode_StreamSink_inference_chunk_Sse(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
throw UnimplementedError('Unreachable ()'); }

@protected String sse_decode_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_prim_u_8_strict(deserializer);
        return utf8.decoder.convert(inner); }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected Str sse_decode_box_autoadd_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(deserializer)); }

@protected LiteRtSession sse_decode_box_autoadd_lite_rt_session(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_lite_rt_session(deserializer)); }

@protected double sse_decode_f_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getFloat32(); }

@protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected InferenceChunk sse_decode_inference_chunk(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_token = sse_decode_String(deserializer);
var var_isFinal = sse_decode_bool(deserializer);
var var_tokensPerSecond = sse_decode_f_32(deserializer);
return InferenceChunk(token: var_token, isFinal: var_isFinal, tokensPerSecond: var_tokensPerSecond); }

@protected InferenceEngine sse_decode_inference_engine(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_modelId = sse_decode_model_id(deserializer);
var var_session = sse_decode_lite_rt_session(deserializer);
return InferenceEngine(modelId: var_modelId, session: var_session); }

@protected List<String> sse_decode_list_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <String>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_String(deserializer)); }
        return ans_;
         }

@protected List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getFloat32List(len_); }

@protected Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getFloat32List(len_); }

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected LiteRtSession sse_decode_lite_rt_session(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_backend = sse_decode_String(deserializer);
return LiteRtSession(backend: var_backend); }

@protected ModelId sse_decode_model_id(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return ModelId.values[inner]; }

@protected ModelTier sse_decode_model_tier(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return ModelTier.values[inner]; }

@protected String? sse_decode_opt_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            if (sse_decode_bool(deserializer)) {
                return (sse_decode_String(deserializer));
            } else {
                return null;
            }
             }

@protected Str? sse_decode_opt_box_autoadd_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            if (sse_decode_bool(deserializer)) {
                return (sse_decode_box_autoadd_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(deserializer));
            } else {
                return null;
            }
             }

@protected (Float32List,String) sse_decode_record_list_prim_f_32_strict_string(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_field0 = sse_decode_list_prim_f_32_strict(deserializer);
var var_field1 = sse_decode_String(deserializer);
return (var_field0, var_field1); }

@protected int sse_decode_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8(); }

@protected void sse_decode_unit(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected BigInt sse_decode_usize(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getBigUint64(); }

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.message, serializer); }

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError(BoxError self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as BoxErrorImpl).frbInternalSseEncode(move: true), serializer); }

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxErrorSendSync(BoxError self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as BoxErrorImpl).frbInternalSseEncode(move: true), serializer); }

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(ModelRegistry self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as ModelRegistryImpl).frbInternalSseEncode(move: true), serializer); }

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf(PathBuf self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as PathBufImpl).frbInternalSseEncode(move: true), serializer); }

@protected void sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(ModelRegistry self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as ModelRegistryImpl).frbInternalSseEncode(move: false), serializer); }

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(ModelRegistry self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as ModelRegistryImpl).frbInternalSseEncode(move: false), serializer); }

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPath(Path self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as PathImpl).frbInternalSseEncode(move: false), serializer); }

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlitePool(SqlitePool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as SqlitePoolImpl).frbInternalSseEncode(move: false), serializer); }

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(Str self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as StrImpl).frbInternalSseEncode(move: false), serializer); }

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError(BoxError self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as BoxErrorImpl).frbInternalSseEncode(move: null), serializer); }

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxErrorSendSync(BoxError self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as BoxErrorImpl).frbInternalSseEncode(move: null), serializer); }

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerModelRegistry(ModelRegistry self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as ModelRegistryImpl).frbInternalSseEncode(move: null), serializer); }

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPath(Path self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as PathImpl).frbInternalSseEncode(move: null), serializer); }

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf(PathBuf self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as PathBufImpl).frbInternalSseEncode(move: null), serializer); }

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlitePool(SqlitePool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as SqlitePoolImpl).frbInternalSseEncode(move: null), serializer); }

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(Str self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as StrImpl).frbInternalSseEncode(move: null), serializer); }

@protected void sse_encode_StreamSink_inference_chunk_Sse(RustStreamSink<InferenceChunk> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.setupAndSerialize(codec: SseCodec(
            decodeSuccessData: sse_decode_inference_chunk,
            decodeErrorData: sse_decode_AnyhowException,
        )), serializer); }

@protected void sse_encode_String(String self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer); }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }

@protected void sse_encode_box_autoadd_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(Str self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(self, serializer); }

@protected void sse_encode_box_autoadd_lite_rt_session(LiteRtSession self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_lite_rt_session(self, serializer); }

@protected void sse_encode_f_32(double self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putFloat32(self); }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }

@protected void sse_encode_inference_chunk(InferenceChunk self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.token, serializer);
sse_encode_bool(self.isFinal, serializer);
sse_encode_f_32(self.tokensPerSecond, serializer);
 }

@protected void sse_encode_inference_engine(InferenceEngine self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_model_id(self.modelId, serializer);
sse_encode_lite_rt_session(self.session, serializer);
 }

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_String(item, serializer); } }

@protected void sse_encode_list_prim_f_32_loose(List<double> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putFloat32List(self is Float32List ? self : Float32List.fromList(self)); }

@protected void sse_encode_list_prim_f_32_strict(Float32List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putFloat32List(self); }

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self); }

@protected void sse_encode_lite_rt_session(LiteRtSession self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.backend, serializer);
 }

@protected void sse_encode_model_id(ModelId self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_model_tier(ModelTier self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_opt_String(String? self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs

                sse_encode_bool(self != null, serializer);
                if (self != null) {
                    sse_encode_String(self, serializer);
                }
                 }

@protected void sse_encode_opt_box_autoadd_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(Str? self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs

                sse_encode_bool(self != null, serializer);
                if (self != null) {
                    sse_encode_box_autoadd_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstr(self, serializer);
                }
                 }

@protected void sse_encode_record_list_prim_f_32_strict_string((Float32List,String) self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_f_32_strict(self.$1, serializer);
sse_encode_String(self.$2, serializer);
 }

@protected void sse_encode_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self); }

@protected void sse_encode_unit(void self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected void sse_encode_usize(BigInt self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putBigUint64(self); }
                }
                

            @sealed class BoxErrorImpl extends RustOpaque implements BoxError {
                // Not to be used by end users
                BoxErrorImpl.frbInternalDcoDecode(List<dynamic> wire):
                    super.frbInternalDcoDecode(wire, _kStaticData);

                // Not to be used by end users
                BoxErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative):
                    super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

                static final _kStaticData = RustArcStaticData(
                    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_BoxError,
                    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_BoxError,
                    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_BoxErrorPtr,
                );

                
            }
            @sealed class BoxErrorImpl extends RustOpaque implements BoxError {
                // Not to be used by end users
                BoxErrorImpl.frbInternalDcoDecode(List<dynamic> wire):
                    super.frbInternalDcoDecode(wire, _kStaticData);

                // Not to be used by end users
                BoxErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative):
                    super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

                static final _kStaticData = RustArcStaticData(
                    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_BoxError,
                    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_BoxError,
                    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_BoxErrorPtr,
                );

                
            }
            @sealed class ModelRegistryImpl extends RustOpaque implements ModelRegistry {
                // Not to be used by end users
                ModelRegistryImpl.frbInternalDcoDecode(List<dynamic> wire):
                    super.frbInternalDcoDecode(wire, _kStaticData);

                // Not to be used by end users
                ModelRegistryImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative):
                    super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

                static final _kStaticData = RustArcStaticData(
                    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_ModelRegistry,
                    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_ModelRegistry,
                    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_ModelRegistryPtr,
                );

                 PathBuf get baseDir=>RustLib.instance.api.crateModelRegistryModelRegistryAutoAccessorGetBaseDir(that: this, );


  set baseDir(PathBuf baseDir)=>RustLib.instance.api.crateModelRegistryModelRegistryAutoAccessorSetBaseDir(that: this, baseDir: baseDir);


 Future<PathBuf>  modelPath({required String modelId })=>RustLib.instance.api.crateModelRegistryModelRegistryModelPath(that: this, modelId: modelId);


            }
            @sealed class PathBufImpl extends RustOpaque implements PathBuf {
                // Not to be used by end users
                PathBufImpl.frbInternalDcoDecode(List<dynamic> wire):
                    super.frbInternalDcoDecode(wire, _kStaticData);

                // Not to be used by end users
                PathBufImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative):
                    super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

                static final _kStaticData = RustArcStaticData(
                    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_PathBuf,
                    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_PathBuf,
                    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_PathBufPtr,
                );

                
            }
            @sealed class PathImpl extends RustOpaque implements Path {
                // Not to be used by end users
                PathImpl.frbInternalDcoDecode(List<dynamic> wire):
                    super.frbInternalDcoDecode(wire, _kStaticData);

                // Not to be used by end users
                PathImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative):
                    super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

                static final _kStaticData = RustArcStaticData(
                    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_Path,
                    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_Path,
                    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_PathPtr,
                );

                
            }
            @sealed class SqlitePoolImpl extends RustOpaque implements SqlitePool {
                // Not to be used by end users
                SqlitePoolImpl.frbInternalDcoDecode(List<dynamic> wire):
                    super.frbInternalDcoDecode(wire, _kStaticData);

                // Not to be used by end users
                SqlitePoolImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative):
                    super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

                static final _kStaticData = RustArcStaticData(
                    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_SqlitePool,
                    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_SqlitePool,
                    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_SqlitePoolPtr,
                );

                
            }
            @sealed class StrImpl extends RustOpaque implements Str {
                // Not to be used by end users
                StrImpl.frbInternalDcoDecode(List<dynamic> wire):
                    super.frbInternalDcoDecode(wire, _kStaticData);

                // Not to be used by end users
                StrImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative):
                    super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

                static final _kStaticData = RustArcStaticData(
                    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_Str,
                    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_Str,
                    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_StrPtr,
                );

                
            }