// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `stream_prompt_to_chunks`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StreamSink`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `close`, `new_channel`, `send`

/// Selection function used by the Dart side to pick an appropriate model tier
/// based on lightweight hints about task complexity. Hints are free-form tags
/// such as `"receipt"`, `"analyze"`, or `"length>350"`.
Future<ModelTier> selectModelTierFromHints({required List<String> hints}) =>
    RustLib.instance.api.crateInferenceSelectModelTierFromHints(hints: hints);

/// FRB-friendly wrapper returning a String for easier Dart consumption.
Future<String> frbSelectModelTier({required List<String> hints}) =>
    RustLib.instance.api.crateInferenceFrbSelectModelTier(hints: hints);

/// FRB-friendly wrapper to load a model and store it globally for later inference calls.
/// Returns Ok(()) on success, Err(String) on failure.
Future<void> frbLoadModel({required String modelId}) =>
    RustLib.instance.api.crateInferenceFrbLoadModel(modelId: modelId);

/// FRB-exposed streaming function. Dart will receive a stream of
/// `InferenceChunk` items. This function spawns a background task so the
/// FRB call can return immediately while the stream continues.
Stream<InferenceChunk> inferStream(
        {required String prompt, required ModelTier modelTier}) =>
    RustLib.instance.api
        .crateInferenceInferStream(prompt: prompt, modelTier: modelTier);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < Error + Send + Sync >>>
abstract class BoxError implements RustOpaqueInterface {}

/// Chunk of inference output sent over FRB to Dart.
class InferenceChunk {
  final String token;
  final bool isFinal;
  final double tokensPerSecond;

  const InferenceChunk({
    required this.token,
    required this.isFinal,
    required this.tokensPerSecond,
  });

  @override
  int get hashCode =>
      token.hashCode ^ isFinal.hashCode ^ tokensPerSecond.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InferenceChunk &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          isFinal == other.isFinal &&
          tokensPerSecond == other.tokensPerSecond;
}

/// The InferenceEngine holds the chosen model id and the underlying runtime
/// session. Later tasks will add loading, streaming and delegate logic.
class InferenceEngine {
  final ModelId modelId;
  final LiteRtSession session;

  const InferenceEngine({
    required this.modelId,
    required this.session,
  });

  /// Helper to construct from string id and backend name (convenience for tests)
  static Future<InferenceEngine> fromStrings(
          {required String model, required String backend}) =>
      RustLib.instance.api.crateInferenceInferenceEngineFromStrings(
          model: model, backend: backend);

  /// Load a model from a filesystem path and construct an InferenceEngine.
  ///
  /// Performs a simple existence check of the model file and chooses a
  /// preferred backend based on environment hints. This is a conservative
  ///, testable implementation; real delegate initialization happens later.
  static Future<InferenceEngine> load(
          {required String modelId, required String modelPath}) =>
      RustLib.instance.api.crateInferenceInferenceEngineLoad(
          modelId: modelId, modelPath: modelPath);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Construct a new InferenceEngine from a ModelId and a LiteRtSession.
  /// This is intentionally simple for the scaffolded implementation.
  static Future<InferenceEngine> newInstance(
          {required ModelId modelId, required LiteRtSession session}) =>
      RustLib.instance.api
          .crateInferenceInferenceEngineNew(modelId: modelId, session: session);

  @override
  int get hashCode => modelId.hashCode ^ session.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InferenceEngine &&
          runtimeType == other.runtimeType &&
          modelId == other.modelId &&
          session == other.session;
}

/// A lightweight stub representing a LiteRT session/delegate. In the real
/// implementation this will wrap the actual LiteRT runtime session and
/// hardware delegates (NPU/ANE/GPU/CPU). For Phase 1/2 scaffolding, keep it
/// minimal and testable.
class LiteRtSession {
  final String backend;

  const LiteRtSession({
    required this.backend,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<LiteRtSession> newInstance({required String backend}) =>
      RustLib.instance.api.crateInferenceLiteRtSessionNew(backend: backend);

  @override
  int get hashCode => backend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiteRtSession &&
          runtimeType == other.runtimeType &&
          backend == other.backend;
}

/// Model identifier (E2B = Sentinel, E4B = Auditor)
enum ModelId {
  e2B,
  e4B,
  ;
}

/// Abstract model tier used for routing decisions. Sentinel == E2B (lightweight),
/// Auditor == E4B (heavy-weight analysis).
enum ModelTier {
  sentinel,
  auditor,
  ;
}
