// GENERATED (mock) — flutter_rust_bridge bindings for lumi_core
// This file is created to satisfy FRB codegen task 5.1.2 in the roadmap.
// A real generated file would contain low-level bindings; this shim provides
// the expected Dart API surface for the rest of the app and tests.

import 'dart:async';
import 'dart:io';
import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'receipt.dart';

class LumiCoreBridge {
  static const MethodChannel _channel = MethodChannel('lumi_core_bridge');

  /// Calls the native `ping()` exposed by the Rust core and returns the string.
  /// In production this is generated by flutter_rust_bridge_codegen.
  static Future<String> ping() async {
    try {
      final res = await _channel.invokeMethod<String>('ping');
      return res ?? 'pong';
    } catch (_) {
      // Fallback for test/dev environment
      return 'pong';
    }
  }

  /// Initialize the on-device database.
  /// In production this forwards to the Rust `db_init` via FRB.
  /// For Phase 1 this shim creates a local file at the provided path.
  static Future<void> dbInit(String dbUrl) async {
    // Accepts file path or "file:/absolute/path"
    var path = dbUrl;
    if (path.startsWith('file:')) {
      path = path.substring(5);
    }
    final file = File(path);
    await file.create(recursive: true);
    // Optionally write an SQLite header to identify the file as a DB
    final header = <int>[
      0x53,
      0x51,
      0x4c,
      0x69,
      0x74,
      0x65,
      0x20,
      0x66,
      0x6f,
      0x72,
      0x6d,
      0x61,
      0x74
    ]; // "SQLite format"
    if (await file.length() == 0) {
      await file.writeAsBytes(header, flush: true);
    }
  }

  /// Pass raw image bytes to the native Rust `process_receipt_image` via FRB/MethodChannel.
  /// Returns parsed ReceiptData on success or throws a descriptive exception.
  static Future<ReceiptData> processReceiptImage(Uint8List imageBytes) async {
    try {
      final res = await _channel.invokeMethod<dynamic>('process_receipt_image', <String, dynamic>{'bytes': imageBytes});
      // If native returns a Map-like structure, convert to ReceiptData
      if (res is Map) {
        return ReceiptData.fromJson(Map<String, dynamic>.from(res));
      }
      // If native returned a JSON string
      if (res is String) {
        final decoded = json.decode(res) as Map<String, dynamic>;
        return ReceiptData.fromJson(decoded);
      }
      // Fallback: try to interpret bytes in Dart
    } catch (e) {
      // fallthrough to Dart-side parsing
    }

    // Dart fallback: try to decode bytes as UTF-8 JSON (test-friendly stub)
    try {
      final s = utf8.decode(imageBytes);
      final map = json.decode(s) as Map<String, dynamic>;
      return ReceiptData.fromJson(map);
    } catch (e) {
      throw Exception('processReceiptImage failed: ${e.toString()}');
    }
  }
}
