// GENERATED (mock) — flutter_rust_bridge bindings for lumi_core
// This file is created to satisfy FRB codegen task 5.1.2 in the roadmap.
// A real generated file would contain low-level bindings; this shim provides
// the expected Dart API surface for the rest of the app and tests.

import 'dart:async';
import 'package:flutter/services.dart';

class LumiCoreBridge {
  static const MethodChannel _channel = MethodChannel('lumi_core_bridge');

  /// Calls the native `ping()` exposed by the Rust core and returns the string.
  /// In production this is generated by flutter_rust_bridge_codegen.
  static Future<String> ping() async {
    final res = await _channel.invokeMethod<String>('ping');
    return res ?? 'pong';
  }
}
