// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `models_base_dir`
// These functions are ignored because they have generic arguments: `new`

Future<String> computeSha256({required Path path}) =>
    RustLib.instance.api.crateModelRegistryComputeSha256(path: path);

Future<bool> checkModelReady(
        {required Path baseDir,
        required String modelId,
        Str? expectedSha256}) =>
    RustLib.instance.api.crateModelRegistryCheckModelReady(
        baseDir: baseDir, modelId: modelId, expectedSha256: expectedSha256);

/// Stubbed progress: real download implementation updates progress via shared state or a file.
Future<double> getDownloadProgress({required String modelId}) =>
    RustLib.instance.api
        .crateModelRegistryGetDownloadProgress(modelId: modelId);

/// FRB-friendly wrapper: check if a model file exists and (optionally) matches expected SHA.
/// This uses LUMI_MODEL_DIR env var if present, else the platform data dir, else temp.
Future<bool> frbCheckModelReady(
        {required String modelId, String? expectedSha256}) =>
    RustLib.instance.api.crateModelRegistryFrbCheckModelReady(
        modelId: modelId, expectedSha256: expectedSha256);

/// FRB-friendly wrapper for download progress. Currently stubbed to 0.0.
Future<double> frbGetDownloadProgress({required String modelId}) =>
    RustLib.instance.api
        .crateModelRegistryFrbGetDownloadProgress(modelId: modelId);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ModelRegistry>>
abstract class ModelRegistry implements RustOpaqueInterface {
  PathBuf get baseDir;

  set baseDir(PathBuf baseDir);

  Future<PathBuf> modelPath({required String modelId});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Path>>
abstract class Path implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PathBuf>>
abstract class PathBuf implements RustOpaqueInterface {}
