// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Prepare a multimodal prompt by encoding the image as a base64 data URI and
/// injecting it into the receipt OCR prompt template.
/// The prompt template is embedded at compile time from `prompts/receipt_ocr.txt`.
Future<String> prepareReceiptOcrPrompt({required List<int> imageBytes}) =>
    RustLib.instance.api
        .crateReceiptPrepareReceiptOcrPrompt(imageBytes: imageBytes);

/// Process raw image bytes and attempt to extract receipt data.
/// Current implementation: if bytes decode as UTF-8 JSON matching ReceiptData, parse and return it.
/// Otherwise returns an Err describing the failure. This is a deterministic, unit-testable stub
/// that will be replaced by a true multimodal OCR + model pipeline later.
Future<ReceiptData> processReceiptImage({required List<int> imageBytes}) =>
    RustLib.instance.api
        .crateReceiptProcessReceiptImage(imageBytes: imageBytes);

class LineItem {
  final String description;
  final double amount;

  const LineItem({
    required this.description,
    required this.amount,
  });

  @override
  int get hashCode => description.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineItem &&
          runtimeType == other.runtimeType &&
          description == other.description &&
          amount == other.amount;
}

class ReceiptData {
  final String vendorName;
  final double totalAmount;
  final String currency;
  final String date;
  final List<LineItem> lineItems;

  const ReceiptData({
    required this.vendorName,
    required this.totalAmount,
    required this.currency,
    required this.date,
    required this.lineItems,
  });

  @override
  int get hashCode =>
      vendorName.hashCode ^
      totalAmount.hashCode ^
      currency.hashCode ^
      date.hashCode ^
      lineItems.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiptData &&
          runtimeType == other.runtimeType &&
          vendorName == other.vendorName &&
          totalAmount == other.totalAmount &&
          currency == other.currency &&
          date == other.date &&
          lineItems == other.lineItems;
}
