// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'db.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `DateTimeFromNaive`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Run a sentinel scan against the provided SqlitePool and return a report.
Future<SentinelReport> runSentinelScanWithPool({required SqlitePool pool}) =>
    RustLib.instance.api.crateSentinelRunSentinelScanWithPool(pool: pool);

Future<SentinelReport> runSentinelScan() =>
    RustLib.instance.api.crateSentinelRunSentinelScan();

class SentinelReport {
  final int untaggedCount;
  final List<String> missingDays;
  final Uint64List incompleteMileage;

  const SentinelReport({
    required this.untaggedCount,
    required this.missingDays,
    required this.incompleteMileage,
  });

  @override
  int get hashCode =>
      untaggedCount.hashCode ^
      missingDays.hashCode ^
      incompleteMileage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SentinelReport &&
          runtimeType == other.runtimeType &&
          untaggedCount == other.untaggedCount &&
          missingDays == other.missingDays &&
          incompleteMileage == other.incompleteMileage;
}
