// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'db.dart';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Insert a transaction into the provided SQLite pool.
/// Returns the inserted (or existing) row id on success.
Future<String> logTransactionWithPool(
        {required SqlitePool pool,
        required String vendor,
        required double amount,
        required String currency,
        required String category,
        required String date,
        Str? receiptPath}) =>
    RustLib.instance.api.crateToolsLogTransactionWithPool(
        pool: pool,
        vendor: vendor,
        amount: amount,
        currency: currency,
        category: category,
        date: date,
        receiptPath: receiptPath);

/// FRB/Tool-facing wrapper. This uses the LUMI_DB_URL env var if set; otherwise
/// falls back to a local file-based `lumi.db` in the current working dir.
/// The function is exposed to Rig as a tool and returns the inserted row ID on success.
Future<String> logTransaction(
        {required String vendor,
        required double amount,
        required String currency,
        required String category,
        required String date,
        String? receiptPath}) =>
    RustLib.instance.api.crateToolsLogTransaction(
        vendor: vendor,
        amount: amount,
        currency: currency,
        category: category,
        date: date,
        receiptPath: receiptPath);

/// Query transactions with optional filters. Returns a vector of TransactionSummary.
Future<List<TransactionSummary>> queryTransactionsWithPool(
        {required SqlitePool pool,
        Str? category,
        Str? dateFrom,
        Str? dateTo,
        int? limit}) =>
    RustLib.instance.api.crateToolsQueryTransactionsWithPool(
        pool: pool,
        category: category,
        dateFrom: dateFrom,
        dateTo: dateTo,
        limit: limit);

/// FRB/Tool wrapper for querying transactions.
Future<List<TransactionSummary>> queryTransactions(
        {String? category, String? dateFrom, String? dateTo, int? limit}) =>
    RustLib.instance.api.crateToolsQueryTransactions(
        category: category, dateFrom: dateFrom, dateTo: dateTo, limit: limit);

/// Insert a mileage log into the provided SQLite pool.
/// Calculates IRS deduction at $0.67/mile (2026 rate) and returns the inserted row id and deduction.
Future<MileageLogResult> logMileageWithPool(
        {required SqlitePool pool,
        required double distanceMiles,
        required String startLocation,
        required String endLocation,
        required String date,
        required String purpose}) =>
    RustLib.instance.api.crateToolsLogMileageWithPool(
        pool: pool,
        distanceMiles: distanceMiles,
        startLocation: startLocation,
        endLocation: endLocation,
        date: date,
        purpose: purpose);

/// FRB/Tool-facing wrapper for logging mileage.
Future<MileageLogResult> logMileage(
        {required double distanceMiles,
        required String startLocation,
        required String endLocation,
        required String date,
        required String purpose}) =>
    RustLib.instance.api.crateToolsLogMileage(
        distanceMiles: distanceMiles,
        startLocation: startLocation,
        endLocation: endLocation,
        date: date,
        purpose: purpose);

Future<List<TransactionSummary>> semanticSearch(
        {required String query, int? topK}) =>
    RustLib.instance.api.crateToolsSemanticSearch(query: query, topK: topK);

Future<FinancialSummary> getSummaryWithPool(
        {required SqlitePool pool, required String period}) =>
    RustLib.instance.api
        .crateToolsGetSummaryWithPool(pool: pool, period: period);

Future<FinancialSummary> getSummary({required String period}) =>
    RustLib.instance.api.crateToolsGetSummary(period: period);

class FinancialSummary {
  final String period;
  final double totalExpenses;
  final List<(String, double)> topCategories;
  final double totalMiles;
  final double estimatedDeduction;
  final double? workingHours;

  const FinancialSummary({
    required this.period,
    required this.totalExpenses,
    required this.topCategories,
    required this.totalMiles,
    required this.estimatedDeduction,
    this.workingHours,
  });

  @override
  int get hashCode =>
      period.hashCode ^
      totalExpenses.hashCode ^
      topCategories.hashCode ^
      totalMiles.hashCode ^
      estimatedDeduction.hashCode ^
      workingHours.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FinancialSummary &&
          runtimeType == other.runtimeType &&
          period == other.period &&
          totalExpenses == other.totalExpenses &&
          topCategories == other.topCategories &&
          totalMiles == other.totalMiles &&
          estimatedDeduction == other.estimatedDeduction &&
          workingHours == other.workingHours;
}

/// Result returned after logging mileage.
class MileageLogResult {
  final String id;
  final double deductionAmount;

  const MileageLogResult({
    required this.id,
    required this.deductionAmount,
  });

  @override
  int get hashCode => id.hashCode ^ deductionAmount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MileageLogResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          deductionAmount == other.deductionAmount;
}

/// A compact summary of a transaction returned to callers.
class TransactionSummary {
  final String id;
  final String? vendor;
  final double amount;
  final String currency;
  final String? category;
  final PlatformInt64 timestamp;
  final bool isTagged;

  const TransactionSummary({
    required this.id,
    this.vendor,
    required this.amount,
    required this.currency,
    this.category,
    required this.timestamp,
    required this.isTagged,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      vendor.hashCode ^
      amount.hashCode ^
      currency.hashCode ^
      category.hashCode ^
      timestamp.hashCode ^
      isTagged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          vendor == other.vendor &&
          amount == other.amount &&
          currency == other.currency &&
          category == other.category &&
          timestamp == other.timestamp &&
          isTagged == other.isTagged;
}
