// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Validate email using a permissive RFC-like regex (case-insensitive).
Future<bool> validateEmail({required String email}) =>
    RustLib.instance.api.crateValidatorsValidateEmail(email: email);

/// Validate password minimal constraints: at least 8 characters.
Future<bool> validatePassword({required String password}) =>
    RustLib.instance.api.crateValidatorsValidatePassword(password: password);

/// Validate terms checkbox — must be true.
Future<bool> validateTerms({required bool accepted}) =>
    RustLib.instance.api.crateValidatorsValidateTerms(accepted: accepted);
