// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EmbeddingRecord`


            /// Initialize a simple on-disk vector DB placeholder for Lumi.
///
/// For Phase 1 this creates the directory and a sentinel file and provides a
/// minimal "transaction_embeddings" table backed by JSON files so unit tests
/// can run without pulling in LanceDB native dependencies.
Future<void>  vectorDbInit({required String dbPath }) => RustLib.instance.api.crateVectorDbVectorDbInit(dbPath: dbPath);

/// Upsert an embedding record into the on-disk "transaction_embeddings" table.
Future<void>  upsertEmbedding({required String dbPath , required String id , required List<double> embedding , required String metadata }) => RustLib.instance.api.crateVectorDbUpsertEmbedding(dbPath: dbPath, id: id, embedding: embedding, metadata: metadata);

/// Retrieve an embedding record by ID.
Future<(Float32List,String)>  getEmbedding({required String dbPath , required String id }) => RustLib.instance.api.crateVectorDbGetEmbedding(dbPath: dbPath, id: id);

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < Error >>>
                abstract class BoxError implements RustOpaqueInterface {
                    

                    
                }
                
            