// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'db.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<String> addVendorFenceWithPool(
        {required SqlitePool pool,
        required String name,
        required double lat,
        required double lng}) =>
    RustLib.instance.api.crateVendorFenceAddVendorFenceWithPool(
        pool: pool, name: name, lat: lat, lng: lng);

Future<List<VendorFence>> getAllFencesWithPool({required SqlitePool pool}) =>
    RustLib.instance.api.crateVendorFenceGetAllFencesWithPool(pool: pool);

Future<void> incrementVisitWithPool(
        {required SqlitePool pool, required String fenceId}) =>
    RustLib.instance.api
        .crateVendorFenceIncrementVisitWithPool(pool: pool, fenceId: fenceId);

Future<String> addVendorFence(
        {required String name, required double lat, required double lng}) =>
    RustLib.instance.api
        .crateVendorFenceAddVendorFence(name: name, lat: lat, lng: lng);

Future<List<VendorFence>> getAllFences() =>
    RustLib.instance.api.crateVendorFenceGetAllFences();

Future<void> incrementVisit({required String fenceId}) =>
    RustLib.instance.api.crateVendorFenceIncrementVisit(fenceId: fenceId);

class VendorFence {
  final String id;
  final String vendorName;
  final double lat;
  final double lng;
  final double radiusMeters;
  final PlatformInt64 visitCount;
  final String? lastVisited;

  const VendorFence({
    required this.id,
    required this.vendorName,
    required this.lat,
    required this.lng,
    required this.radiusMeters,
    required this.visitCount,
    this.lastVisited,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      vendorName.hashCode ^
      lat.hashCode ^
      lng.hashCode ^
      radiusMeters.hashCode ^
      visitCount.hashCode ^
      lastVisited.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VendorFence &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          vendorName == other.vendorName &&
          lat == other.lat &&
          lng == other.lng &&
          radiusMeters == other.radiusMeters &&
          visitCount == other.visitCount &&
          lastVisited == other.lastVisited;
}
