import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:go_router/go_router.dart';

import '../../core/router.dart';

class NotificationService {
  static final NotificationService _instance = NotificationService._();
  NotificationService._();
  factory NotificationService() => _instance;

  final FlutterLocalNotificationsPlugin _plugin = FlutterLocalNotificationsPlugin();

  // In-memory recent alerts to support notification grouping summary.
  final List<String> _recentSentinelAlerts = [];

  // Exposed for unit tests / reviewer verification
  int lastSummaryCount = 0;
  List<String> lastSummaryLines = [];

  Future<void> initialize() async {
    const android = AndroidInitializationSettings('@mipmap/ic_launcher');
    final ios = DarwinInitializationSettings(
      requestSoundPermission: true,
      requestBadgePermission: true,
      requestAlertPermission: true,
    );

    await _plugin.initialize(
      InitializationSettings(android: android, iOS: ios),
      onDidReceiveNotificationResponse: (NotificationResponse response) {
        final String payload = response.payload ?? '';
        _handlePayloadTap(payload);
      },
      // For older plugin versions, onSelectNotification may be used by tests.
      onDidReceiveBackgroundNotificationResponse: null,
    );

    // If the app was launched via a notification, handle the initial payload.
    try {
      final details = await _plugin.getNotificationAppLaunchDetails();
      if (details != null && details.didNotificationLaunchApp) {
        final payload = details.notificationResponse?.payload ?? '';
        if (payload.isNotEmpty) {
          // Defer slightly to ensure router is ready.
          Future.microtask(() => _handlePayloadTap(payload));
        }
      }
    } catch (_) {
      // ignore
    }

    // Create channel for sentinel alerts
    const channel = AndroidNotificationChannel(
      'sentinel_alerts',
      'Sentinel Alerts',
      description: 'Alerts generated by the Sentinel background scans',
      importance: Importance.defaultImportance,
    );

    try {
      await _plugin.resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
          ?.createNotificationChannel(channel);
    } catch (e) {
      if (kDebugMode) debugPrint('failed to create notification channel: $e');
    }

    if (kDebugMode) debugPrint('[NotificationService] initialized');
  }

  /// Public helper: process a sentinel report into grouping state and a summary.
  /// Returns a map: { 'count': int, 'lines': List<String>, 'summaryTitle': String, 'summaryBody': String }
  Map<String, dynamic> processSentinelReport(Map<String, dynamic> report) {
    final String body = buildSentinelBody(report);
    // Record the latest alert line
    _recentSentinelAlerts.add(body);
    // keep only last 5 alerts
    if (_recentSentinelAlerts.length > 5) _recentSentinelAlerts.removeAt(0);

    lastSummaryLines = List.unmodifiable(_recentSentinelAlerts);
    lastSummaryCount = lastSummaryLines.length;

    final summaryTitle = lastSummaryCount == 1 ? 'Lumi: 1 alert' : 'Lumi: $lastSummaryCount alerts';
    final summaryBody = lastSummaryLines.join('\n');

    return {
      'count': lastSummaryCount,
      'lines': lastSummaryLines,
      'summaryTitle': summaryTitle,
      'summaryBody': summaryBody,
    };
  }

  Future<void> showSentinelAlert(Map<String, dynamic> report) async {
    final int untagged = (report['untagged_count'] is int) ? report['untagged_count'] as int : (report['untagged_count'] is num ? (report['untagged_count'] as num).toInt() : 0);
    final int missing = (report['missing_days'] is List) ? (report['missing_days'] as List).length : 0;
    final int incomplete = (report['incomplete_mileage'] is List) ? (report['incomplete_mileage'] as List).length : 0;

    final List<String> parts = [];
    if (untagged > 0) parts.add('$untagged untagged transaction${untagged==1? '':'s'}');
    if (missing > 0) parts.add('$missing missing day${missing==1? '':'s'}');
    if (incomplete > 0) parts.add('$incomplete incomplete mileage log${incomplete==1? '':'s'}');

    final String body = parts.isNotEmpty ? parts.join('; ') : 'No issues detected.';
    final String title = parts.isNotEmpty ? 'Lumi: Action needed' : 'Lumi: Scan complete';

    final payload = jsonEncode({'type': 'sentinel', 'report': report});

    // Update grouping state and build summary info
    final summary = processSentinelReport(report);
    final List<String> summaryLines = summary['lines'] as List<String>;
    final String summaryTitle = summary['summaryTitle'] as String;
    final String summaryBody = summary['summaryBody'] as String;

    // Individual alert notification (grouped)
    final androidIndividual = AndroidNotificationDetails(
      'sentinel_alerts',
      'Sentinel Alerts',
      channelDescription: 'Alerts generated by the Sentinel background scans',
      importance: Importance.defaultImportance,
      priority: Priority.defaultPriority,
      styleInformation: BigTextStyleInformation(body),
      groupKey: 'lumi_sentinel_group',
    );

    final iosIndividual = DarwinNotificationDetails(threadIdentifier: 'lumi.sentinel');

    final int individualId = DateTime.now().millisecondsSinceEpoch.remainder(1 << 31);

    try {
      await _plugin.show(
        individualId,
        title,
        body,
        NotificationDetails(android: androidIndividual, iOS: iosIndividual),
        payload: payload,
      );
    } catch (e) {
      if (kDebugMode) debugPrint('[NotificationService] individual show failed: $e');
    }

    // Summary (group) notification
    final inboxStyle = InboxStyleInformation(
      summaryLines,
      contentTitle: summaryTitle,
      summaryText: 'Tap to review in Lumi',
    );

    final androidSummary = AndroidNotificationDetails(
      'sentinel_alerts',
      'Sentinel Alerts',
      channelDescription: 'Alerts generated by the Sentinel background scans',
      importance: Importance.defaultImportance,
      styleInformation: inboxStyle,
      groupKey: 'lumi_sentinel_group',
      // setAsGroupSummary is supported in newer plugin versions; include if available.
      setAsGroupSummary: true,
    );

    final iosSummary = DarwinNotificationDetails(threadIdentifier: 'lumi.sentinel');

    try {
      // fixed id 9001 reserved for sentinel summary
      await _plugin.show(
        9001,
        summaryTitle,
        summaryLines.isNotEmpty ? '${summaryLines.length} recent alerts' : summaryBody,
        NotificationDetails(android: androidSummary, iOS: iosSummary),
        payload: payload,
      );
    } catch (e) {
      if (kDebugMode) debugPrint('[NotificationService] summary show failed: $e');
    }
  }

  Future<void> showGeofenceAlert(String vendorName, {double? lat, double? lng}) async {
    final title = 'Leaving $vendorName?';
    final body = 'Tap to log your purchase or snap a receipt.';
    final payload = jsonEncode({'type': 'geofence', 'vendor': vendorName, 'lat': lat, 'lng': lng});

    final androidDetails = AndroidNotificationDetails(
      'sentinel_alerts',
      'Sentinel Alerts',
      channelDescription: 'Alerts generated by the Sentinel background scans',
      importance: Importance.defaultImportance,
      groupKey: 'lumi_sentinel_group',
    );

    final iosDetails = DarwinNotificationDetails(threadIdentifier: 'lumi.sentinel');

    try {
      await _plugin.show(9002, title, body, NotificationDetails(android: androidDetails, iOS: iosDetails), payload: payload);
    } catch (e) {
      if (kDebugMode) debugPrint('[NotificationService] geofence show failed: $e');
    }
  }

  // Exposed helper to build the sentinel notification body (useful for unit tests)
  String buildSentinelBody(Map<String, dynamic> report) {
    final int untagged = (report['untagged_count'] is int) ? report['untagged_count'] as int : (report['untagged_count'] is num ? (report['untagged_count'] as num).toInt() : 0);
    final int missing = (report['missing_days'] is List) ? (report['missing_days'] as List).length : 0;
    final int incomplete = (report['incomplete_mileage'] is List) ? (report['incomplete_mileage'] as List).length : 0;

    final List<String> parts = [];
    if (untagged > 0) parts.add('$untagged untagged transaction${untagged==1? '':'s'}');
    if (missing > 0) parts.add('$missing missing day${missing==1? '':'s'}');
    if (incomplete > 0) parts.add('$incomplete incomplete mileage log${incomplete==1? '':'s'}');

    return parts.isNotEmpty ? parts.join('; ') : 'No issues detected.';
  }

  // Exposed helper to build the sentinel notification title
  String buildSentinelTitle(Map<String, dynamic> report) {
    final body = buildSentinelBody(report);
    return body == 'No issues detected.' ? 'Lumi: Scan complete' : 'Lumi: Action needed';
  }

  /// Handle a tapped notification payload by parsing it and navigating the app.
  void _handlePayloadTap(String payloadJson) {
    try {
      final routeMap = NotificationService.parsePayloadToRoute(payloadJson);
      final String route = routeMap['route'] as String? ?? '/';
      final params = routeMap['params'];

      final ctx = appNavigatorKey.currentContext;
      if (ctx != null) {
        try {
          // Use GoRouter to navigate so app-level guards and redirects are applied.
          if (params != null) {
            GoRouter.of(ctx).go(route, extra: params);
          } else {
            GoRouter.of(ctx).go(route);
          }
        } catch (e) {
          if (kDebugMode) debugPrint('[NotificationService] GoRouter navigation failed: $e');
          // Fallback to navigator by name if available.
          try {
            appNavigatorKey.currentState?.pushNamed(route);
          } catch (_) {
            // ignore fallback failures
          }
        }
      } else {
        if (kDebugMode) debugPrint('[NotificationService] No navigator context available to handle notification tap for route: $route');
      }
    } catch (e) {
      if (kDebugMode) debugPrint('[NotificationService] _handlePayloadTap error: $e');
    }
  }

  /// Parse a notification payload JSON and return a routing map suitable for deep-link handling.
  /// Returns: { 'route': String, 'params': Map<String,dynamic>? }
  static Map<String, dynamic> parsePayloadToRoute(String payloadJson) {
    try {
      final Map<String, dynamic> payload = jsonDecode(payloadJson) as Map<String, dynamic>;
      final String? type = payload['type'] as String?;
      if (type == 'sentinel') {
        return {'route': '/dashboard', 'params': null};
      } else if (type == 'geofence') {
        final String vendor = payload['vendor'] as String? ?? '';
        final String prefill = 'Just left $vendor. What did you buy?';
        return {'route': '/home', 'params': {'openChat': true, 'prefill': prefill, 'vendor': vendor}};
      }
    } catch (e) {
      if (kDebugMode) debugPrint('[NotificationService] parsePayloadToRoute failed: $e');
    }
    return {'route': '/', 'params': null};
  }
}
