import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

class NotificationService {
  static final NotificationService _instance = NotificationService._();
  NotificationService._();
  factory NotificationService() => _instance;

  final FlutterLocalNotificationsPlugin _plugin = FlutterLocalNotificationsPlugin();

  Future<void> initialize() async {
    const android = AndroidInitializationSettings('@mipmap/ic_launcher');
    final ios = DarwinInitializationSettings(
      requestSoundPermission: true,
      requestBadgePermission: true,
      requestAlertPermission: true,
    );

    await _plugin.initialize(
      InitializationSettings(android: android, iOS: ios),
      // payload handling is left to app routing layer
    );

    // Create channel for sentinel alerts
    const channel = AndroidNotificationChannel(
      'sentinel_alerts',
      'Sentinel Alerts',
      description: 'Alerts generated by the Sentinel background scans',
      importance: Importance.defaultImportance,
    );

    try {
      await _plugin.resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
          ?.createNotificationChannel(channel);
    } catch (e) {
      if (kDebugMode) debugPrint('failed to create notification channel: $e');
    }

    if (kDebugMode) debugPrint('[NotificationService] initialized');
  }

  Future<void> showSentinelAlert(Map<String, dynamic> report) async {
    final int untagged = (report['untagged_count'] is int) ? report['untagged_count'] as int : (report['untagged_count'] is num ? (report['untagged_count'] as num).toInt() : 0);
    final int missing = (report['missing_days'] is List) ? (report['missing_days'] as List).length : 0;
    final int incomplete = (report['incomplete_mileage'] is List) ? (report['incomplete_mileage'] as List).length : 0;

    final List<String> parts = [];
    if (untagged > 0) parts.add('$untagged untagged transaction${untagged==1? '':'s'}');
    if (missing > 0) parts.add('$missing missing day${missing==1? '':'s'}');
    if (incomplete > 0) parts.add('$incomplete incomplete mileage log${incomplete==1? '':'s'}');

    final String body = parts.isNotEmpty ? parts.join('; ') : 'No issues detected.';
    final String title = parts.isNotEmpty ? 'Lumi: Action needed' : 'Lumi: Scan complete';

    final payload = jsonEncode({'type': 'sentinel', 'report': report});

    final androidDetails = AndroidNotificationDetails(
      'sentinel_alerts',
      'Sentinel Alerts',
      channelDescription: 'Alerts generated by the Sentinel background scans',
      importance: Importance.defaultImportance,
      priority: Priority.defaultPriority,
      styleInformation: BigTextStyleInformation(body),
    );
    final iosDetails = DarwinNotificationDetails();

    await _plugin.show(
      9001, // fixed id for sentinel summary
      title,
      body,
      NotificationDetails(android: androidDetails, iOS: iosDetails),
      payload: payload,
    );
  }

  Future<void> showGeofenceAlert(String vendorName, {double? lat, double? lng}) async {
    final title = 'Leaving $vendorName?';
    final body = 'Tap to log your purchase or snap a receipt.';
    final payload = jsonEncode({'type': 'geofence', 'vendor': vendorName, 'lat': lat, 'lng': lng});

    final androidDetails = AndroidNotificationDetails(
      'sentinel_alerts',
      'Sentinel Alerts',
      channelDescription: 'Alerts generated by the Sentinel background scans',
      importance: Importance.defaultImportance,
    );

    await _plugin.show(9002, title, body, NotificationDetails(android: androidDetails), payload: payload);
  }

  // Exposed helper to build the sentinel notification body (useful for unit tests)
  String buildSentinelBody(Map<String, dynamic> report) {
    final int untagged = (report['untagged_count'] is int) ? report['untagged_count'] as int : (report['untagged_count'] is num ? (report['untagged_count'] as num).toInt() : 0);
    final int missing = (report['missing_days'] is List) ? (report['missing_days'] as List).length : 0;
    final int incomplete = (report['incomplete_mileage'] is List) ? (report['incomplete_mileage'] as List).length : 0;

    final List<String> parts = [];
    if (untagged > 0) parts.add('$untagged untagged transaction${untagged==1? '':'s'}');
    if (missing > 0) parts.add('$missing missing day${missing==1? '':'s'}');
    if (incomplete > 0) parts.add('$incomplete incomplete mileage log${incomplete==1? '':'s'}');

    return parts.isNotEmpty ? parts.join('; ') : 'No issues detected.';
  }

  // Exposed helper to build the sentinel notification title
  String buildSentinelTitle(Map<String, dynamic> report) {
    final body = buildSentinelBody(report);
    return body == 'No issues detected.' ? 'Lumi: Scan complete' : 'Lumi: Action needed';
  }

  /// Parse a notification payload JSON and return a routing map suitable for deep-link handling.
  /// Returns: { 'route': String, 'params': Map<String,dynamic>? }
  static Map<String, dynamic> parsePayloadToRoute(String payloadJson) {
    try {
      final Map<String, dynamic> payload = jsonDecode(payloadJson) as Map<String, dynamic>;
      final String? type = payload['type'] as String?;
      if (type == 'sentinel') {
        return {'route': '/dashboard', 'params': null};
      } else if (type == 'geofence') {
        final String vendor = payload['vendor'] as String? ?? '';
        return {'route': '/home', 'params': {'openCamera': true, 'vendor': vendor}};
      }
    } catch (e) {
      if (kDebugMode) debugPrint('[NotificationService] parsePayloadToRoute failed: $e');
    }
    return {'route': '/', 'params': null};
  }
}
