#!/usr/bin/env bash
set -euo pipefail

TEMPLATE_VSCODE=".vscode/mcp.json.template"
ENV_TEMPLATE=".env.test.template"

mkdir -p .vscode
cat > "$TEMPLATE_VSCODE" <<'JSON'
{
  "servers": {
    "appwrite": {
      "command": "uvx",
      "args": ["mcp-server-appwrite"],
      "env": {
        "APPWRITE_ENDPOINT": "http://localhost/v1",
        "APPWRITE_PROJECT_ID": "lumi-dev",
        "APPWRITE_API_KEY": "<REPLACE_WITH_API_KEY>"
      }
    }
  }
}
JSON

cat > "$ENV_TEMPLATE" <<'ENV'
APPWRITE_ENDPOINT=http://localhost/v1
APPWRITE_PROJECT_ID=lumi-dev
APPWRITE_API_KEY=<REPLACE_WITH_API_KEY>
TEST_USER_EMAIL=test@lumi.com
TEST_USER_PASSWORD=TestPass123!
TEST_RESET_EMAIL=reset@lumi.com
MAILHOG_URL=http://localhost:8025
ENV

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cat > "$REPO_ROOT/scripts/APPWRITE_SETUP_INSTRUCTIONS.txt" <<'TXT'
Appwrite manual setup steps (also generated by this script):

1) Start Appwrite (docker compose -f docker-compose.appwrite.yml up -d)
2) Open http://localhost/console
3) Create a project named: lumi-dev
4) Add a Flutter platform with bundle ID: com.lumi.app
5) Enable Email/Password authentication
6) Configure SMTP (use Mailhog in docker-compose for dev):
   Host: mailhog
   Port: 1025
   Secure: false
7) Copy the generated API key into .vscode/mcp.json.template (replace <REPLACE_WITH_API_KEY>)
8) Rename .env.test.template -> .env.test and use with --dart-define-from-file when running integration tests

If Appwrite is reachable, consider using the Appwrite REST API or MCP automation to perform these steps programmatically.
TXT

echo "Generated $TEMPLATE_VSCODE and $ENV_TEMPLATE and scripts/APPWRITE_SETUP_INSTRUCTIONS.txt"

echo "Next steps:"
echo "  - Edit .vscode/mcp.json.template and replace <REPLACE_WITH_API_KEY> with a real key."
echo "  - Move .env.test.template -> .env.test when ready."
